### ISSUE TITLE
cifar100

### ISSUE THREAD

**Issue by shruum** [chaht01/Co2L#3]
Hi, 
I was trying to run Cifar100 dataset (5 tasks). But with Cifar10 hyperparameters, I am getting low accuracy.
Do you have a better setting for cifar100? Do you have any results for cifar100?

Please let me know. Thanks

**Comment by chaht01** [comment]
Hi, shruum.
Unfortunately, since I've tried cifar100 long time ago and at that time I didn't have enough time to get great performance, there's no results to share.
However, I recommend you not to use hyperparameter which was used for cifar10. Rather, I recommend you to start from using ones with DER(Dark Experience for General Continual Learning: a Strong, Simple Baseline) paper. 

Thanks
